
export enum EstablishmentSpecialtyEnum {
  BRASILEIRA = 'BRASILEIRA',
  MEXICANA = 'MEXICANA',
  JAPONESA = 'JAPONESA',
  CHINESA = 'CHINESA',
  ITALIANA = 'ITALIANA',
  HAVAIANA = 'HAVAIANA',
  NENHUMA = 'NENHUMA'
}
