
export enum EstablishmentTypeEnum {
  RESTAURANT = 'RESTAURANTE',
  BAR = 'BAR',
  PIZZARIA = 'PIZZARIA',
  HAMBURGUERIA = 'HAMBURGUERIA',
  ADEGA = 'ADEGA',
  TABACARIA = 'TABACARIA',
  DOCERIA = 'DOCERIA',
  MERCADO = 'MERCADO'
}
