
export enum EstablishmentTypeEnum {
  RESTAURANTE = 'RESTAURANTE',
  BAR = 'BAR',
  PIZZARIA = 'PIZZARIA',
  HAMBURGUERIA = 'HAMBURGUERIA',
  ADEGA = 'ADEGA',
  TABACARIA = 'TABACARIA',
  DOCERIA = 'DOCERIA',
  MERCADO = 'MERCADO',
  CHURRASCARIA = 'CHURRASCARIA',
  CAFETERIA = 'CAFETERIA',
  EMPORIO = 'EMPORIO'
}
